services:
  postgres:
    image: postgres:15
    container_name: inegi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TMHzabusito88
      POSTGRES_DB: population_data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: ./mipipeline
    container_name: inegi-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: TMHzabusito88
      DB_NAME: population_data
      INPUT_PATH: /app/data/datospobla.csv
      OUTPUT_PATH: /app/output/poblacionclean.csv
      LOG_DIR: /app/logs
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./logs:/app/logs

  airflow-init:
    image: apache/airflow:2.9.2
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:TMHzabusito88@postgres:5432/population_data
      - AIRFLOW__CORE__FERNET_KEY=fernet_key_example_123456789
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
                    airflow users create -u airflow -p airflow -r Admin -e admin@example.com -f Air -l Flow"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/dags/data
      - ./output:/opt/airflow/dags/output
      - ./logs:/opt/airflow/dags/logs
      - ./airflow/plugins:/opt/airflow/plugins

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow-webserver
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:TMHzabusito88@postgres:5432/population_data
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/dags/data
      - ./output:/opt/airflow/dags/output
      - ./logs:/opt/airflow/dags/logs
      - ./airflow/plugins:/opt/airflow/plugins

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow-scheduler
    restart: unless-stopped
    depends_on:
      airflow-webserver:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:TMHzabusito88@postgres:5432/population_data
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/dags/data
      - ./output:/opt/airflow/dags/output
      - ./logs:/opt/airflow/dags/logs
      - ./airflow/plugins:/opt/airflow/plugins

volumes:
  pgdata:
